### ISSUE TITLE
Yahoo API return fahrenheit even 'c' parameter is set 

### ISSUE THREAD

**Issue by jyp66** [userexec/Pi-Kitchen-Dashboard#4]
Seems that Yahoo Weather API has changed, it returns temperature always in fahrenheit

**Comment by userexec** [comment]
Thanks for the heads up. I'm not seeing any documentation on how to get Yahoo! to return that data in Celsius anymore, so I've moved temperature conversion into a function in weather.js that runs as the temperatures are being inserted onto the page. Setting the unit to 'c' should work again with this update.
